---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-nginx-configmap
data:
  agent.json: |
    {
      "log_level": "DEBUG",
      "enable_script_checks": true
    }
  nginx_service.json: |
    {
      "service": {
        "name": "nginx",
        "tags": ["primary"],
        "port": 80,
        "checks": [
          {
            "http": "http://localhost",
            "interval": "10s"
          }
        ]
      }
    }