---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-watcher
  labels:
    app: consul-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-watcher
  template:
    metadata:
      labels:
        app: consul-watcher
    spec:
      containers:
      - name: consul-watcher
        image: consul_client_base:1.0.0
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
          - "agent"
          - "-bind=0.0.0.0"
          - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
          - "-domain=cluster.local"
          - "-data-dir=/consul/data"
          - "-config-dir=/consul/config"
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - consul leave
        volumeMounts:
          - name: client-watcher-configmap
            mountPath: /consul/config
      volumes:
        - name: client-watcher-configmap
          configMap:
            name: client-watcher-configmap